order_spin_box: 5
spike_fwhm_spin_box: 0.0
laser_wl_spinbox: 784.7
max_ccd_value_spin_box: 65536
neg_grad_factor_spin_box: 2
cm_range_start: 310.0
cm_range_end: 2000.0
trim_range_start: 370.0
trim_range_end: 1780.0
emsc_pca_n_spinBox: 8
normalizing_method_comboBox: 'SNV'
smoothing_method_comboBox: 'MLESG'
window_length_spinBox: 5
whittaker_lambda_spinBox: 1
smooth_polyorder_spinBox: 2
sigma_spinBox: 4
kaiser_beta_doubleSpinBox: 14.0
emd_noise_modes_spinBox: 1
eemd_trials_spinBox: 10
alpha_factor: 0.99
bl_method_comboBox: 'ExModPoly'
cost_func_comboBox: 'asymmetric_truncated_quadratic'
eta: 0.5
half_window: 3
fraction: 0.2
tol: 0.0000001
lambda: 100_000
min_length: 2
max_iter: 1000
num_std: 3.0
p: 0.01
peak_ratio: 0.5
polynome_degree: 8
quantile: 0.0001
scale: .5
sections: 32
spline_degree: 3
average_function: 'Mean'
average_errorbar: 'ci'
average_n_boot_spin_box: 100
average_level_spin_box: 95
interval_start: 310.0
interval_end: 2000.0
fit_method: 'Least-Squares, Trust Region Reflective method'
guess_method_cb: 'Average'
max_dx_guess: 12.0
max_noise_level: 30.
l_ratio: .25
select_percentile_spin_box: 50
dataset_type_cb: 'Decomposed'
refit_score: "recall_score"
feature_display_max_spinBox: 50
random_state_sb: 0
test_data_ratio_spinBox: 10