peak_shape_names: ['Gaussian', 'Split Gaussian', 'Skewed Gaussian', 'Lorentzian',
                   'Split Lorentzian', 'Voigt', 'Split Voigt', 'Skewed Voigt', 'Pseudo Voigt',
                   'Split Pseudo Voigt', 'Pearson4', 'Split Pearson4', 'Pearson7', 'Split Pearson7']
fitting_methods:
  Least-Squares, Trust Region Reflective method: 'least_squares'
  Levenberg-Marquardt: 'leastsq'
  Basin-hopping: 'basinhopping'
  Adaptive Memory Programming for Global Optimization: 'ampgo'
  Nelder-Mead: 'nelder'
  L-BFGS-B: 'lbfgsb'
  Powell: 'powell'
  Conjugate-Gradient: 'cg'
  Cobyla: 'cobyla'
  BFGS: 'bfgs'
  Truncated Newton: 'tnc'
  trust-region for constrained optimization: 'trust-constr'
  Sequential Linear Squares Programming: 'slsqp'